### ISSUE TITLE
Scan fails when using existing bulk_extractor reports

### ISSUE THREAD

**Issue by ShellyYBlack** [bulk-reviewer/bulk-reviewer#46]
Hi, I'm attempting to start a new session using existing bulk_extractor reports, but the scan doesn't complete. I gave the session a name, and chose the source directory and path to the reports. I can confirm the source directory is in the same place it was when the reports were created.

Here is the message that pops up in Bulk Reviewer:
```
[6530] Failed to execute script br_processor Traceback (most recent call last): File "br_processor.py", line 1107, in File "br_processor.py", line 1081, in main File "br_processor.py", line 585, in read_features_to_db File "br_processor.py", line 594, in parse_feature_file File "/Users/travis/build/bulk-reviewer/bulk-reviewer/env/lib/python3.7/codecs.py", line 322, in decode UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd4 in position 0: invalid continuation byte
```

I don't see errors, but this is what I see in the log:
```
2021-11-18 12:44:41,459 - INFO - Running script in processing mode. Name: 19db9518-0909-463e-b8a1-c304800e2b91. Source: /Users/borndigital/born_digital/19db9518-0909-463e-b8a1-c304800e2b91/logical.
2021-11-18 12:44:41,486 - INFO - Writing source file metadata to database
2021-11-18 12:49:14,208 - INFO - Reading feature files to database
```

**Comment by tw4l** [comment]
Hi @ShellyYBlack, sorry for not responding to this sooner! Brian just reminded me in a similar Brunnhilde issue. I will look into this and try to get a fix out shortly!

**Comment by tw4l** [comment]
@ShellyYBlack Could you confirm what version of Bulk Reviewer has the issue, and if it's still reproducible with the newest version? Thank you!

**Comment by ShellyYBlack** [comment]
I tried it on two different machines. One had 0.2.0 and the other had 0.3.0. Thanks!

**Comment by tw4l** [comment]
Hi @ShellyYBlack! Can you try this release candidate and see if it fixes your issue?

https://github.com/bulk-reviewer/bulk-reviewer/releases/tag/v0.3.1-rc1

Thanks!

**Comment by tw4l** [comment]
You should be able to remove the old application by dragging it from Applications to the trash, and then re-install via the new dmg.

**Comment by ShellyYBlack** [comment]
Terrific! I downloaded the release candidate, and the session now loads.
